"use client";

import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { createAdminCurriculumVersion, getAccessToken, loadAdminCurriculumVersions, loadAdminGrades, loadAdminSubjects, transitionAdminCurriculumVersion, compareAdminCurriculumVersion, type AdminCurriculumVersion, type AdminGradeLevel, type AdminSubject } from "../auth/adminAuth";
import { CurriculumShell } from "./CurriculumShell";

function requestId() { return `admin-version-${Date.now()}-${Math.random().toString(36).slice(2)}`; }
export function CurriculumVersionsPage() {
  const router = useRouter(); const [versions, setVersions] = useState<AdminCurriculumVersion[]>([]); const [grades, setGrades] = useState<AdminGradeLevel[]>([]); const [subjects, setSubjects] = useState<AdminSubject[]>([]); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const reload = async () => setVersions(await loadAdminCurriculumVersions());
  useEffect(() => { if (!getAccessToken()) { router.replace("/auth/Login"); return; } queueMicrotask(() => { void Promise.all([reload(), loadAdminGrades(), loadAdminSubjects()]).then(([, g, s]) => { setGrades(g); setSubjects(s); }).catch((error) => setMessage(error instanceof Error ? error.message : "Unable to load curriculum versions.")); }); }, [router]);
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); setBusy(true); try { await createAdminCurriculumVersion({ grade_level_id: String(form.get("grade")), subject_id: String(form.get("subject")), label: String(form.get("label")), change_summary: String(form.get("summary")) }); await reload(); event.currentTarget.reset(); setMessage("Draft version created."); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to create version."); } finally { setBusy(false); } }
  async function action(version: AdminCurriculumVersion, name: "submit-review" | "publish" | "archive" | "reject") { const reason = name === "reject" || name === "archive" ? window.prompt("Reason for this decision:") ?? undefined : undefined; if ((name === "reject" || name === "archive") && !reason) return; setBusy(true); try { await transitionAdminCurriculumVersion(version.curriculum_version_id, name, requestId(), reason); await reload(); setMessage(`Version ${name} completed.`); } catch (error) { setMessage(error instanceof Error ? error.message : "Version action failed."); } finally { setBusy(false); } }
  async function compare(version: AdminCurriculumVersion) { try { const result = await compareAdminCurriculumVersion(version.curriculum_version_id); setMessage(`Compare: ${JSON.stringify(result)}`); } catch (error) { setMessage(error instanceof Error ? error.message : "Compare failed."); } }
  return <CurriculumShell active="Versions" title="Curriculum Versions" subtitle="Draft, review, publish, and archive curriculum safely." searchPlaceholder="Search versions"><form onSubmit={create} className="mb-6 grid gap-3 rounded-xl border border-line bg-surface p-5 md:grid-cols-4"><select required name="grade" className="rounded bg-surface-2 p-3">{grades.map((grade) => <option key={grade.id} value={grade.grade_level_id}>{grade.name}</option>)}</select><select required name="subject" className="rounded bg-surface-2 p-3">{subjects.map((subject) => <option key={subject.id} value={subject.subject_id}>{subject.grade} — {subject.name}</option>)}</select><input required name="label" placeholder="Version label, e.g. 2026.1" className="rounded bg-surface-2 p-3"/><input required name="summary" placeholder="Change summary" className="rounded bg-surface-2 p-3"/><button disabled={busy} className="rounded bg-indigo-600 p-3 font-bold">Create draft</button></form>{message && <p className="mb-4 rounded border border-cyan-600 p-3 text-sm">{message}</p>}<section className="overflow-x-auto rounded-xl border border-line"><table className="w-full text-left text-sm"><thead><tr className="border-b border-line"><th className="p-4">Version</th><th>Status</th><th>Summary</th><th className="p-4">Actions</th></tr></thead><tbody>{versions.map((version) => <tr key={version.curriculum_version_id} className="border-b border-line"><td className="p-4">{version.label}<br/><span className="text-xs text-slate-400">{version.curriculum_version_id}</span></td><td>{version.status}</td><td>{version.change_summary}</td><td className="p-4 space-x-2"><button onClick={() => compare(version)}>Compare</button>{version.status === "draft" && <button disabled={busy} onClick={() => action(version, "submit-review")}>Submit</button>}{version.status === "in_review" && <><button disabled={busy} onClick={() => action(version, "publish")}>Publish</button><button disabled={busy} onClick={() => action(version, "reject")}>Reject</button></>}{version.status !== "archived" && <button disabled={busy} onClick={() => action(version, "archive")}>Archive</button>}</td></tr>)}</tbody></table></section></CurriculumShell>;
}
